### ISSUE TITLE
usb lacking

### ISSUE THREAD

**Issue by wdthompson** [manjaro-arm/opi5-images#14]
There should be 8 hubs...lsusb |grep hub,,, not 4
OR  sudo lshw | grep -i -B4 -A3 'usb@'   ,,, and you will notice NO xHCI
and so the vertical port is dead
(on a "5" ,, not 5b or 5+)

**Comment by wdthompson** [comment]
some more,, digging in dmesg,,BTW 2 of the hubs missing are xhci, usb3, no mention of xhci in dmesg
This is, I think, a dtb misconfiguration 
Looking up phy-supply property in node /syscon@fd5d8000/usb2-phy@8000/host-port failed
also---/syscon@fd5dc000/usb2-phy@c000/host-port failed

**Comment by wdthompson** [comment]
and some more,, 6 hubs now,,NOT the vertical or usbC
In dts  @fc fd 00 00 change disabled to okay
still the 2 errors above, this is probably the missing ports,
I don't know how to fix

**Comment by spikerguy** [comment]
Yes not all usb's were enabled before. 

Should have better support from todays update.
