### ISSUE TITLE
Boots to an Unusable state.

### ISSUE THREAD

**Issue by CovLinuxGuy** [manjaro-arm/opi5-images#15]
December 2023 image boots to a unusable state, GUI desktop is displayed in a non-usable format. Suggest testing on actual Hardware before release.
![20231220_182022](https://github.com/manjaro-arm/opi5-images/assets/154463320/5f823ff2-0b25-4f5c-b4cf-a80805146017)

**Comment by CovLinuxGuy** [comment]
Update:  2712/2023 Same Boot Issue, Display is badly distorted and is unusable, have had a poke around and believe its due to the fact that the .dtb file for the Orange Pi 5B is still missing, would recommend a lable placed to note not to boot this image on the 5B model as is highly unstable. REQUEST COMPLETELY SEPERATE 5B IMAGE TO BE CREATED.

**Comment by wdthompson** [comment]
You might try 1113, it gave me a display (opi5).  1225 gave same screen as you show
1225 still has ONLY 4 hubs, no usbC or vetical usb port (should show 8, and they should work)

**Comment by CovLinuxGuy** [comment]
I did try the 1113 version, the problem with it is that, when you go to update, it messes the whole install up again by changing existing settings to the newer 1225 and then buggers up. Its such a shame as i think this would be an ace distro to run and install on the OPI5B, just most of the additional things you get, such as WiFi and Bluetooth, the Emmc and extra USB's are basically useless. Thank you though for all your infiormation and your efforts to remedy the situation, I dont think its anything to do with the edid system, i think it a Wayland issue as the XFCE4 1225 image displays perfectly, but also lacks WiFi and Bluetooth (there also seems to be no installed WiFi and Bluetooth Management and driver software, as plugging in a very common WiFi USB dongle doest show in the network system settings. Its like all the modules for WiFi and BT are not included in the image) 

In My HUmble Opinion, This is a poorly created image, possibly due to the lack of actual hardware testing and the resistance of the builders to use non-mainstream .dbt files and kernels to build the images. (see comments on the official ARM channel on the Discord for Manjaro refusing use of the supplied .dtb files from a working install of ARMBIAN) 

I persoanlly belive that we wont get a working viable image for the OPI5B from Manjaro untill they physically obtain test hardware and they shouldnt release an image for a device unless they actualy have hardware to test their built images on.

**Comment by CovLinuxGuy** [comment]
Well, we have another version released that fails to boot properly....DO NOT USE THIS IMAGE...IT IS DEFECTIVE FOR KDE USERS....... Stop building these images untill they actually work properly. They are obviously taking up space on a server somewhere, space I assume is being paid for in some way. just quit the build process untill these images have been TESTED AND VERIFIED TO WORK PROPERLY.....You are wasting our time and your money not testing these properly.

**Comment by CovLinuxGuy** [comment]
Just wanted to update this issue thread. The issue still exists and makes the image unusable on the OPI5B. The above image of the desktop is still relevant. Serious issues with this image, and we need a complete rebuild with accurate on-hardware testing. If no hardware is available for testing, remove the image and wait for concise testing abilities.

**Comment by CovLinuxGuy** [comment]
UPDATE : IMAGE 20240506 BORKED ON ORANGE PI 5 B, Tested from Mulitple brands of Fast Micro-SD cards and boots to a complete black screen after initial boot-up logo screen. Now totally useless and unusable for anything. Please remove this image as it is defective and doesnt work. seems to be automatically generated and has no official use whatsoever. WISH THIS WOULD ACTUALLY BE LOOKED INTO, BUT AS OF YET.....SWEET NOTHING TO BE SHOWN AND NO UPDATES ON A POSSIBLE FIX. IMAGE DEAD AS OF 17/05/2024.

**Comment by spikerguy** [comment]
Wow, IDK why I am not getting notifications for all issues raised

yes HDMi was not the best before. Just updated the kernel with rk3588 patches. Should have better hdmi and panthor support. have not tested yet.

**Comment by CovLinuxGuy** [comment]
Heya SpikerGuy

Thank you for replying. (and i mean that honestly, not in any sarcastic way I promise). I just want to use Manjaro on my OP5B. Will we get a new image generated? and Will the Onboard Wifi/Bluetooth moduel on the 5B be recognised so as to include the Wifi networking applications and subsystems. Also, I have one with an OnBoard EMMC module, will that be picked up in the fstab system and be available to install to? (A LOT OF QUESTIONS, I KNOW.....:-) ) Oh and while I've got your ear, Can you pass my name on to whomever needs it for a test unit of the Orange PI Neo as Id love to help test and dev for it:-)

**Comment by spikerguy** [comment]
I have OPI-5-Plus and I am currently testing it now. 

It should work if the opi5b have unisoc wifi then it should work too but I will have to prepare an image for that device with wifi firmware added to it.

**Comment by CovLinuxGuy** [comment]
Thanks Buddy, That would be so freakin amazing. I absolutely love Manjaro as an OS, and I mean that...Passionate Nerd here...

I look forward to seeing the new image available.....got me an Micro-SD card here awaiting your efforts. 

Thank you again buddy. Much Appreciated.

**Comment by spikerguy** [comment]
Try images from [here](https://github.com/manjaro-arm/opi5-images/releases/tag/20240608)

I have not tested it as I don't have this device. I have just tested it on opi5-plus and it works. 
IDK about wifi though.

**Comment by CovLinuxGuy** [comment]
Thanks muchly, Will download it, burn it, test it and feedback ;-) 
Results to follow.....oh and for the Orange PI Neo Testing, Please give them my email...covlinuxguy@gmail.com
THANK YOU SO OS OS MUCH....:-)

**Comment by CovLinuxGuy** [comment]
![20240609_004028](https://github.com/manjaro-arm/opi5-images/assets/154463320/b967331e-e090-4271-a2e4-a05211f01465)


Heya Striker, 

Had this error when starting up,  Also, No WiFi module is detected or EMMC seen by the system...I'm assuming the quick creation of the image has caused this... Just for feedback:-)

Thanks again... We have progress though, I can actually boot this to a point I can use in some way and interact with:-) so.... More work to be done.... anything I can do at my end?:-)

**Comment by CovLinuxGuy** [comment]
Oh and to add, GPU drivers work and, All cores and RAM are recognised. If this helps, the Text on the WiFi module is AP6275P. Things are looking up buddy:-)

**Comment by spikerguy** [comment]
Calamares issue is resolved in the latest image which I pushed few hours after you downloaded that image. 

For wifi I will have to look for the right firmware for that chip. I will test it on other boards which have same chip. 

I will close this issue for now as it is bootable and hdmi, gpu and usb is working fine.

**Comment by CovLinuxGuy** [comment]
Thanks again mate. Very much appreciated for all your help and hard work. Will be brilliant to be able to use WiFi at some point in the future. Will you keep me posted on the progress of that ? Would be great to keep in touch:-)  

Yet again, Thank you so much again:-)
