### ISSUE TITLE
Doesn't boot

### ISSUE THREAD

**Issue by atropos112** [manjaro-arm/opi5-images#5]
I am sorry, I might be missing something obvious I am somewhat new to this. 

I flashed img.xz onto sd card (using BalenaEtcher) and tried to boot off that on Orange Pi 5, all I got is black screen. Is there something I am missing ?

**Comment by 333337lee** [comment]
Same for me. Orange Pi 5

**Comment by spikerguy** [comment]
Hello 
These images does not have HDMI out as there is no hdmi support in Mainline linux kernel yet.

Please use uart cable to see it boot using sdcard only.
